### ISSUE TITLE
NameError: name 'xrange' is not defined

### ISSUE THREAD

**Issue by BigZeroKim** [llSourcell/How-to-Generate-Music-Demo#12]
Hello, when generator.py is run i get the following error:

Traceback (most recent call last):
  File "generator.py", line 193, in <module>
    main(sys.argv)
  File "generator.py", line 188, in main
    generate(data_fn, out_fn, N_epochs)
  File "generator.py", line 107, in generate
    chords, abstract_grammars = get_musical_data(data_fn)
  File "C:\Users\kem63\Documents\Workspace\deepjazz-master\preprocess.py", line 130, in get_musical_data
    measures, chords = __parse_midi(data_fn)
  File "C:\Users\kem63\Documents\Workspace\deepjazz-master\preprocess.py", line 51, in __parse_midi
    for i in xrange(len(comp_stream)):
NameError: name 'xrange' is not defined

I am on Windows 10 Python 3.6

**Comment by TVI-BIZ** [comment]
change xrange to range
xrange - Python 2
range - Python 3
