### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'mode'

### ISSUE THREAD

**Issue by ekt1701** [llSourcell/How-to-Generate-Music-Demo#2]
Hello, when generator.py is run I get the following error:

`Traceback (most recent call last):
  File "generator.py", line 193, in <module>
    main(sys.argv)
  File "generator.py", line 188, in main
    generate(data_fn, out_fn, N_epochs)
  File "generator.py", line 107, in generate
    chords, abstract_grammars = get_musical_data(data_fn)
  File "/Users/EKT2014/dlmusic/preprocess.py", line 130, in get_musical_data
    measures, chords = __parse_midi(data_fn)
  File "/Users/EKT2014/dlmusic/preprocess.py", line 37, in __parse_midi
    melody_voice.insert(0, key.KeySignature(sharps=1, mode='major'))
TypeError: __init__() got an unexpected keyword argument 'mode'`

I am on Mac OSX 10.11.6 Python 2.7

**Comment by F-Serra** [comment]
Same here.
Deleting the `mode='major'` part fixed it.
The doc doesn't mention a second argument:
http://web.mit.edu/music21/doc/moduleReference/moduleKey.html#music21.key.KeySignature

**Comment by ekt1701** [comment]
@F-Serra Thanks for the fix

**Comment by benwiz** [comment]
Alternative fix is to use key.Key() (http://web.mit.edu/music21/doc/moduleReference/moduleKey.html#music21.key.Key)

With optional second argument of mode.

`melody_voice.insert(0, key.Key('G', 'major'))`
