### ISSUE TITLE
music21.exceptions21.StreamException: attempting to access index 5 while elements is of size ..

### ISSUE THREAD

**Issue by abosmond** [llSourcell/How-to-Generate-Music-Demo#7]
When I use another mid file and try to generate it, I got an error ::
"music21.exceptions21.StreamException: attempting to access index 5 while elements is of size 1."

I trace it and found on preprocess.py ::
midi_data = converter.parse(data_fn)    # Get melody part, compress into single voice.
melody_stream = midi_data[5]     # For Metheny piece, Melody is Part #5.

That's array create an error. Do you have any idea which part I should change?

**Comment by srianbury** [comment]
Did you ever find a solution to this?

**Comment by srianbury** [comment]
Same here.  If I change the array to the correct length I get: attempting to access index 4 while elements is of size 4.  Does that make any sense for an error?  Did you find a solution?

**Comment by momo1986** [comment]
Same problem.
When I generate the music in bach-style:
I got the error:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/music21/stream/__init__.py", line 390, in __getitem__
    match = self.elements[k]
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generator.py", line 202, in <module>
    main(sys.argv)
  File "generator.py", line 197, in main
    generate(data_fn, out_fn, N_epochs)
  File "generator.py", line 116, in generate
    chords, abstract_grammars = get_musical_data(data_fn)
  File "/fast/junyan/MidiGeneration/How-to-Generate-Music-Demo/preprocess.py", line 131, in get_musical_data
    measures, chords = __parse_midi(data_fn)
  File "/fast/junyan/MidiGeneration/How-to-Generate-Music-Demo/preprocess.py", line 25, in __parse_midi
    melody_stream = midi_data[5]     # For Metheny piece, Melody is Part #5.
  File "/root/anaconda3/lib/python3.6/site-packages/music21/stream/__init__.py", line 394, in __getitem__
    (k, len(self.elements)))
music21.exceptions21.StreamException: attempting to access index 5 while elements is of size 2
